In [1]:
import numpy as np

In [3]:
# Create one dimensional array - unicode datatype
np_city = np.array(['New York City','Los Angeles','Miami','Houston'])
np_city

array(['New York City', 'Los Angeles', 'Miami', 'Houston'], dtype='<U13')

In [5]:
# Dimension value
np_city.ndim

1

In [12]:
# Two dimensional array
np_city_and_state = np.array([['New York City','Los Angeles','Miami','Houston'],['New York','California','Florida','Texas']])
np_city_and_state


array([['New York City', 'Los Angeles', 'Miami', 'Houston'],
       ['New York', 'California', 'Florida', 'Texas']], dtype='<U13')

In [20]:
# One dimensional array
print('Dimension = ' + str(np_city.ndim))
print('Shape = ' + str(np_city.shape))
print('Size = ' + str(np_city.size))


Dimension = 1
Shape = (4,)
Size = 4


In [23]:
# Two dimensional array
print('Dimension = ' + str(np_city_and_state.ndim))
print('Shape = ' + str(np_city_and_state.shape))
print('Size = ' + str(np_city_and_state.size))

Dimension = 2
Shape = (2, 4)
Size = 8


In [31]:
#NumPy uses the indices of the elements in each array to carry out basic operations. 
#In this case, where we are looking at a dataset of four cyclists during two trials, 
#vector addition of the arrays gives the required output.

first_trial_cyclist = [10,15,17,26]
second_trial_cyclist = [12,11,21,24]
np_first = np.array(first_trial_cyclist)
np_second = np.array(second_trial_cyclist)
print(np_first)
print(np_second)
total = np_first + np_second
print(total)


[10 15 17 26]
[12 11 21 24]
[22 26 38 50]


In [34]:
#You can access an entire row of an array by referencing its axis index. 
cyclist_trials = np.array([[10,15,17,26],[12,11,21,24]])
first_trial = cyclist_trials[0]
first_trial

array([10, 15, 17, 26])

In [36]:
second_trial = cyclist_trials[1]
second_trial

array([12, 11, 21, 24])

In [42]:
#You can refer the indices of the elements in an array to access them. 
#You can also select a particular index of more than one axis at a time. 
print(cyclist_trials)
print(cyclist_trials[1][2])

[[10 15 17 26]
 [12 11 21 24]]
21


In [45]:
#Boolean arrays are useful when you need to select a dataset according to set criteria. 
#Here, the original dataset contains test scores of two students. 
#You can use a Boolean array to choose only the scores that are above a given value.
test_scores = np.array([[83,71,57,63],[54,68,81,45]])
passing_scores = test_scores > 60
passing_scores

array([[ True,  True, False,  True],
       [False,  True,  True, False]])

In [46]:
# using passing_scores as argument for test_scores
test_scores[passing_scores]

array([83, 71, 63, 68, 81])

In [54]:
# NumPy has ndarray.view() method which is a new array object that looks at the same data of the original array. 
# Change in dimensions of the new array doesn’t change dimensions of the original.
# Referred to as shallow copy

boroughs_in_nyc = np.array(['Manhattan','Bronx','Brooklyn','Staten Island','Queens'])
boroughs_view = boroughs_in_nyc.view()
boroughs_view[3] = 'Central Park'
boroughs_view

array(['Manhattan', 'Bronx', 'Brooklyn', 'Central Park', 'Queens'],
      dtype='<U13')

In [55]:
# notice that the original array has changed Staten Island to Central Park as well
boroughs_in_nyc

array(['Manhattan', 'Bronx', 'Brooklyn', 'Central Park', 'Queens'],
      dtype='<U13')

In [63]:
#views are often used to take a slice of the original array
reduced_view = boroughs_in_nyc[1:3]
reduced_view

array(['Bronx', 'Brooklyn'], dtype='<U13')

In [64]:
#Original stays the same
boroughs_view

array(['Manhattan', 'Bronx', 'Brooklyn', 'Central Park', 'Queens'],
      dtype='<U13')

In [65]:
# The copy() method returns a copy of the original array stored at a new location. 
# The copy doesn’t share data or memory with the original array. The modifications are not reflected. 
# The copy function is also known as deep copy.

boroughs_in_nyc = np.array(['Manhattan','Bronx','Brooklyn','Staten Island','Queens'])
boroughs_copy = boroughs_in_nyc.copy()
boroughs_copy[3] = 'Central Park'
boroughs_copy

array(['Manhattan', 'Bronx', 'Brooklyn', 'Central Park', 'Queens'],
      dtype='<U13')

In [66]:
# Notice that original array stays the same.
boroughs_in_nyc

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Queens'],
      dtype='<U13')

In [72]:
# square root
np_sqrt = np.sqrt([4,9,16,25])
np_sqrt


3.141592653589793

In [73]:
from numpy import pi
np.cos(pi)

-1.0

In [77]:
# floor returns largest integer of any value in the array
np.floor([1,5,2.6,7.8,4,-3,-2.3])

array([ 1.,  5.,  2.,  7.,  4., -3., -3.])

In [79]:
# Exponential function
ar=np.array([1,2,3])
ar=np.exp(ar)
print(ar)

[ 2.71828183  7.3890561  20.08553692]


In [82]:
# The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. 
# Arithmetic operations on arrays are usually done on corresponding elements.
# If two arrays are of exactly the same shape, then these operations are smoothly performed.
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a + b 
print(c)

[11 22 33 44]


In [87]:
a = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]]) 
b = np.array([1,2,3])  
   
print('First array:')
print(a) 
print('\n')
   
print('Second array:') 
print(b)
print('\n')  
   
print('First Array + Second Array') 
c = a + b
print(c)

First array:
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


Second array:
[1 2 3]


First Array + Second Array
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [90]:
# transpose
test_scores = np.array([[83,71,57,63],[54,68,81,45]])
test_scores

array([[83, 71, 57, 63],
       [54, 68, 81, 45]])

In [91]:
test_scores.transpose()

array([[83, 54],
       [71, 68],
       [57, 81],
       [63, 45]])

In [97]:
# To find the inverse of a 2x2 matrix: swap the positions of a and d, 
# put negatives in front of b and c, and divide everything by the determinant (ad-bc).
#[4,-2],[-3,1]
x = np.array([[1,2],[3,4]]) 
y = np.linalg.inv(x) 
print(x)
print (y)


[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [98]:
# Trace sums up diagonal elemes (1 and 4 in the case below)
trace_array = np.array([[1,2],[3,4]]) 
np.trace(trace_array)

5